[package]
authors = ["Diggory Hardy <git@dhardy.name>"]
name = "routing-sims"
version = "0.1.0"

[dependencies]
docopt = "0.6.86"
env_logger = "0.3.5"
log = "0.3.6"
rand = "0.3.14"
rustc-serialize = "0.3.19"
